---
Name: silverstripe-gathercontent
---
SSGatherContent:
  api:
    url: "https://api.gathercontent.com/"
    username:
    key:

  plugin_api:
    url: "https://%%ACCOUNTNAME%%.gathercontent.com/api/0.4/"
    accountname:
    key:
    password: x

  project:

  s3_file_store_url: https://gathercontent.s3.amazonaws.com/
  assets_subfolder: gathercontent
  assets_subfolder_json: "gathercontent/json"
  assets_subfolder_backup: "gathercontent/backup"
  suffix_backup_with_datetime: true
  save_json_files: false
  use_saved_json_files: false
  update_existing: true
  overwrite_files: false
  allow_publish: false

  unique_identifier: GC_ItemID

  processors:
    field: []
    value:
      - "SSGatherContentProcessor::trimString"
      - "SSGatherContentProcessor::removeZeroWidthSpaces"

  mappings:
    classes:

  statuses:
    skip: []
    draft: []
    publish: []

  translations: []
